kind: Service
apiVersion: v1
metadata:
  name: spark-worker
  labels:
    app: spark-worker
  annotations:
    dev.okteto.com/auto-ingress: "true"
    # https://www.okteto.com/docs/cloud/ssl/
spec:
  type: ClusterIP
  ports:
    # okteto 只会暴露第一个
    - name: webui
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    component: spark-worker
